export function configure(aurelia) {
  aurelia.globalResources(
    './ValueConverter/take-form-to',
    './CustomAttributes/Accordion',
    './CustomElements/calendar',
    './CustomAttributes/Dropdown',
    './CustomAttributes/CheckBox',
    './CustomAttributes/Rating',
    './CustomAttributes/Modal',
    './CustomAttributes/Tooltip',
    './CustomAttributes/Menu',
    './CustomAttributes/Tab',
    './CustomElements/pagination',
     './Dialog/account-websites',
    './CustomAttributes/ShowDropDown',
     './Dialog/cu-account-website-Dlg',
     './Dialog/menu-header.html',
     './Dialog/cu-account-Dlg',
     './Dialog/cu-production-Dlg'
     );
}
